# Generated manually for the MVP.
from django.db import migrations, models
import django.db.models.deletion
class Migration(migrations.Migration):
    initial=True
    dependencies=[('auth','0012_alter_user_first_name_max_length')]
    operations=[
        migrations.CreateModel(name='Goal',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('title',models.CharField(max_length=200,unique=True)),('description',models.TextField(blank=True)),('status',models.CharField(default='active',max_length=20))]),
        migrations.CreateModel(name='Person',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=120)),('email',models.EmailField(blank=True,max_length=254)),('active',models.BooleanField(default=True)),('external_source',models.CharField(blank=True,max_length=40)),('external_id',models.CharField(blank=True,max_length=120)),('notes',models.TextField(blank=True)),('user',models.OneToOneField(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='person',to='auth.user'))]),
        migrations.CreateModel(name='Work',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('type',models.CharField(choices=[('project','Project'),('deliverable','Deliverable'),('task','Task')],default='task',max_length=20)),('title',models.CharField(max_length=240)),('description',models.TextField(blank=True)),('planned_start',models.DateField(blank=True,null=True)),('due_date',models.DateField(blank=True,null=True)),('sunset_date',models.DateField(blank=True,null=True)),('outcome',models.TextField(blank=True)),('exit_condition',models.TextField(blank=True)),('status',models.CharField(choices=[('proposed','Proposed'),('ready','Ready'),('in_progress','In Progress'),('blocked','Blocked'),('done','Done'),('cancelled','Cancelled')],default='proposed',max_length=20)),('risk',models.CharField(choices=[('normal','Normal'),('at_risk','At Risk')],default='normal',max_length=20)),('completed_at',models.DateTimeField(blank=True,null=True)),('external_source',models.CharField(blank=True,max_length=40)),('external_id',models.CharField(blank=True,max_length=120)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('collaborators',models.ManyToManyField(blank=True,related_name='collaborations',to='work.person')),('goal',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='work_items',to='work.goal')),('owner',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='owned_work',to='work.person')),('parent',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.CASCADE,related_name='children',to='work.work'))],options={'ordering':['due_date','title']}),
        migrations.CreateModel(name='Dependency',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('depends_on',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='dependents',to='work.work')),('work',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='dependencies',to='work.work'))]),
        migrations.AddConstraint(model_name='dependency',constraint=models.UniqueConstraint(fields=('work','depends_on'),name='unique_dependency')),
        migrations.CreateModel(name='Comment',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('body',models.TextField()),('created_at',models.DateTimeField(auto_now_add=True)),('person',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to='work.person')),('work',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='comments',to='work.work'))]),
        migrations.CreateModel(name='Link',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('title',models.CharField(max_length=160)),('url',models.URLField()),('work',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='links',to='work.work'))]),
        migrations.CreateModel(name='Activity',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('event_type',models.CharField(max_length=80)),('data',models.JSONField(blank=True,default=dict)),('created_at',models.DateTimeField(auto_now_add=True)),('actor',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to='work.person')),('work',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='activity',to='work.work'))],options={'ordering':['-created_at']})
    ]
